baseURL = "https://athul.github.io/archie/"
languageCode = "en-us"
title = "vmamore's blog"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=4
[params]
	favicon="https://img.icons8.com/officel/16/000000/chevron-right.png"
	og_image="https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
	mode="auto"
	useCDN=false
	subtitle = "Hello! My name is Vinicius Mamoré and I'm a Software Developer"
	description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vmamore"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/vinimamore"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "/about"
weight = 3
